# This is the template configuration for OpenTelemetry collector, and is not used by default.
# It is mounted to '/etc/otel-collector/config.yaml' in the otel-collector container.

receivers:
  otlp:
    protocols:
      grpc: # port 4317
      http: # port 4318

exporters:
  logging:
    # If you want to see the contents of spans in output, you can set logLevel to 'debug',
    # but you probably want to configure another exporter - this is mostly here becasue
    # we're not allowed to configure no exporters.
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

  # Add your exporter(s) configuration here. For each exporter, make sure it is enabled
  # in the service configuration below.
  # Refer to our OpenTelemetry docs for information on how to configure different exporters:
  # https://docs.sourcegraph.com/admin/observability/opentelemetry
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
   # Add your exporter(s) configuration here. For each exporter, make sure it is enabled
   # in the service configuration below.
   # Refer to our OpenTelemetry docs for information on how to configure different

extensions:
  health_check:
    endpoint: ":13133"
  zpages:
    endpoint: "localhost:55679"

service:
  telemetry:
    metrics:
      address: ":8888"
  pipelines:
    traces:
      exporters:
        - jaeger
        # Add the name of your exporter(s) here, e.g.:
        - logging
      receivers:
        - otlp # Do not remove this receiver
  extensions:
    # Do not remove these extensions
    - health_check
    - zpages
